data:extend({
  {
    type = "selection-tool",
    name = "agentic-local-build-tool",
    icon = "__base__/graphics/icons/blueprint.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool",
    order = "c[automated-construction]-z[local-companion-build]",
    stack_size = 1,
    select = {
      border_color = { r = 0.2, g = 1, b = 0.2 },
      mode = { "entity-ghost" },
      cursor_box_type = "copy",
    },
    alt_select = {
      border_color = { r = 0.2, g = 1, b = 0.2 },
      mode = { "entity-ghost" },
      cursor_box_type = "copy",
    },
  },
  {
    type = "selection-tool",
    name = "agentic-local-demolish-tool",
    icon = "__base__/graphics/icons/deconstruction-planner.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool",
    order = "c[automated-construction]-z[local-companion-demolish]",
    stack_size = 1,
    select = {
      border_color = { r = 1, g = 0.2, b = 0.2 },
      mode = { "any-entity" },
      cursor_box_type = "not-allowed",
    },
    alt_select = {
      border_color = { r = 1, g = 0.2, b = 0.2 },
      mode = { "any-entity" },
      cursor_box_type = "not-allowed",
    },
  },
  {
    type = "selection-tool",
    name = "agentic-local-patrol-route-tool",
    icon = "__base__/graphics/icons/radar.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool",
    order = "c[automated-construction]-z[local-companion-patrol-route]",
    stack_size = 1,
    select = {
      border_color = { r = 0.25, g = 0.75, b = 1 },
      mode = { "any-tile" },
      cursor_box_type = "copy",
    },
    alt_select = {
      border_color = { r = 0.5, g = 1, b = 0.25 },
      mode = { "any-tile" },
      cursor_box_type = "copy",
    },
  },
  {
    type = "selection-tool",
    name = "agentic-local-blueprint-anchor-tool",
    icon = "__base__/graphics/icons/blueprint.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool",
    order = "c[automated-construction]-z[local-companion-blueprint-anchor]",
    stack_size = 1,
    select = {
      border_color = { r = 0.2, g = 0.6, b = 1 },
      mode = { "any-tile" },
      cursor_box_type = "copy",
    },
    alt_select = {
      border_color = { r = 0.2, g = 0.6, b = 1 },
      mode = { "any-tile" },
      cursor_box_type = "copy",
    },
  },
  {
    type = "selection-tool",
    name = "agentic-local-mine-container-tool",
    icon = "__base__/graphics/icons/steel-chest.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool",
    order = "c[automated-construction]-z[local-companion-mine-container]",
    stack_size = 1,
    select = {
      border_color = { r = 1, g = 0.75, b = 0.1 },
      mode = { "any-entity" },
      cursor_box_type = "copy",
    },
    alt_select = {
      border_color = { r = 1, g = 0.75, b = 0.1 },
      mode = { "any-entity" },
      cursor_box_type = "copy",
    },
  },
  {
    type = "selection-tool",
    name = "agentic-local-production-target-tool",
    icon = "__base__/graphics/icons/inserter.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool",
    order = "c[automated-construction]-z[local-companion-production-target]",
    stack_size = 1,
    select = {
      border_color = { r = 1, g = 0.45, b = 0.1 },
      mode = { "any-entity" },
      cursor_box_type = "copy",
    },
    alt_select = {
      border_color = { r = 1, g = 0.45, b = 0.1 },
      mode = { "any-entity" },
      cursor_box_type = "copy",
    },
  },
  {
    type = "selection-tool",
    name = "agentic-local-output-source-tool",
    icon = "__base__/graphics/icons/assembling-machine-1.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool", order = "c[automated-construction]-z[output-source]", stack_size = 1,
    select = { border_color = { r = 0.2, g = 0.8, b = 1 }, mode = { "any-entity" }, cursor_box_type = "copy" },
    alt_select = { border_color = { r = 0.2, g = 0.8, b = 1 }, mode = { "any-entity" }, cursor_box_type = "copy" },
  },
  {
    type = "selection-tool",
    name = "agentic-local-output-destination-tool",
    icon = "__base__/graphics/icons/steel-chest.png",
    icon_size = 64,
    flags = { "only-in-cursor", "not-stackable", "spawnable" },
    subgroup = "tool", order = "c[automated-construction]-z[output-destination]", stack_size = 1,
    select = { border_color = { r = 0.2, g = 1, b = 0.4 }, mode = { "any-entity" }, cursor_box_type = "copy" },
    alt_select = { border_color = { r = 0.2, g = 1, b = 0.4 }, mode = { "any-entity" }, cursor_box_type = "copy" },
  },
})
