-- AUTO-GENERATED by scripts/build-starter-blueprints.mjs — DO NOT EDIT.
-- Source: BlueprintBooks/*.txt. Regenerate with: npm run blueprints:build
return {
  version = "sha1:c495ec88baf6",
  books = {
    require("scripts.starter_blueprints.book_1"),
    require("scripts.starter_blueprints.book_2"),
    require("scripts.starter_blueprints.book_3"),
    require("scripts.starter_blueprints.book_4"),
  },
}
